"""One authenticated DTLS session's lifetime: the handshake handoff, reading
records, ACKing them, and closing on idle, age, or revocation.

Must never touch the database directly - it queues via storage.ingest_telemetry
and leaves the actual writes to the db worker thread.
"""

import json
import random
import re
import select
import time

import acks
import device_addresses
import identity_guard
import nmu_mailbox
import storage

RECV_BYTES = 8192
SESSION_AGE_JITTER = 0.20
EVENT_ID_RE = re.compile(r"^[0-9]+_[0-9]+$")
MAX_EVENT_ID_LEN = 64


class RecordTimeout(Exception):
    """No datagram arrived within the deadline."""


def valid_event_id(value):
    """Accept only the session-counter IDs generated by AMU and NMU."""
    return (isinstance(value, str) and 0 < len(value) <= MAX_EVENT_ID_LEN
            and EVENT_ID_RE.fullmatch(value) is not None)


def recv_with_timeout(conn, raw_sock, nbytes, timeout_s):
    """Read one record with a timeout that actually works.

    SO_RCVTIMEO cannot be relied on: wolfSSL's own DTLS receive callback
    (src/wolfio.c, EmbedReceiveFrom) recomputes and REWRITES it on every read,
    and once the handshake is done it writes {0,0}, which POSIX reads as
    "block forever". select() has its own clock and never consults that
    socket option, so it is immune.
    """
    try:
        if conn.pending() > 0:
            return conn.recv(nbytes)
    except Exception:
        pass
    ready, _, _ = select.select([raw_sock], [], [], timeout_s)
    if not ready:
        raise RecordTimeout("no datagram within %.1f s" % timeout_s)
    return conn.recv(nbytes)


# REJECTED DESIGN, kept as a warning (2026-08-20): pushing an unsolicited
# question datagram down the device's session, so it could be answered
# without waiting for the device to speak. It fails on BOTH sides with this
# wolfSSL binding: the device can only safely read when it already expects a
# reply (an unsolicited read blocks inside wolfSSL past its own timeout and
# starves the sender - measured, see FINDINGS #32), so a pushed datagram is
# read at a moment nobody is listening for it. Questions therefore ride on
# the ACK the device is already waiting for - acks.build_ack's "q" - which is
# the one path that has been in production for both device types unchanged.


def peer_common_name(conn):
    """Device identity from the VERIFIED certificate - never from the payload."""
    try:
        cert = conn.getpeercert()
    except Exception:
        return None
    if not cert:
        return None
    for rdn in cert.get("subject", ()):
        for key, value in rdn:
            if key == "commonName":
                return value
    return None


def serve_session(conn, raw, device_id, config_store, packet_queue,
                  max_session_age_s, log, mailbox_db_path=None):
    """Read records off one authenticated session until the age policy expires
    it, the peer closes, or it goes quiet."""
    # Each session gets its own limit inside the jitter band, so no two devices
    # expire together even when they handshake together.
    age_limit = max_session_age_s * random.uniform(
        1.0 - SESSION_AGE_JITTER, 1.0 + SESSION_AGE_JITTER)
    idle_limit = config_store.idle_timeout_for(device_id)
    # monotonic, not time(): this measures a DURATION, and the wall clock can
    # step. A server that boots without internet and reaches NTP minutes later
    # gets its clock corrected underneath a running session, which would make
    # every open session appear to age by the size of the correction (forcing
    # needless re-handshakes) or to grow younger (delaying the age-limit
    # checkpoint). monotonic only ever counts forward at a steady rate and is
    # immune to both. The wall clock is still what devices are told, in "t" -
    # that one has to be the real date.
    started = time.monotonic()
    records = 0
    duplicates = 0
    log("[%s] session up, age limit %.1fs (base %.0fs +/-%d%% jitter), "
        "idle limit %.0fs"
        % (device_id, age_limit, max_session_age_s, int(SESSION_AGE_JITTER * 100),
           idle_limit))

    while True:
        try:
            data = recv_with_timeout(conn, raw, RECV_BYTES, idle_limit)
        except RecordTimeout:
            log("[%s] idle past %.0fs - closing" % (device_id, idle_limit))
            break
        except Exception as error:
            log("[%s] read error: %s" % (device_id, type(error).__name__))
            break
        if not data:
            break
        if data.strip() == b"BYE":
            log("[%s] peer said goodbye" % device_id)
            break

        try:
            inner = json.loads(data.decode("utf-8"))
        except (ValueError, UnicodeDecodeError):
            continue

        event = inner.get("event")
        if not valid_event_id(event):
            log("[%s] malformed event id - dropping record without ACK" % device_id)
            continue

        if not config_store.is_allowed(device_id):
            log("[%s] REVOKED mid-session - closing immediately" % device_id)
            break

        age = time.monotonic() - started
        expired = age >= age_limit

        # "qr" (query reply): the answer to a question piggybacked on a
        # PAST ack (see acks.build_ack's "q"), riding back on whatever this
        # device was already about to send - not a new connection. Captured
        # before the ack is built so a reply and a fresh question can both
        # be in flight in the same record without racing each other.
        if mailbox_db_path is not None and "qr" in inner:
            nmu_mailbox.deliver_reply(mailbox_db_path, device_id, inner["qr"])
            log("[%s] delivered a queued question's reply" % device_id)

        ack = acks.build_ack(config_store, device_id, event, reauth=expired,
                             mailbox_db_path=mailbox_db_path)
        try:
            conn.send(json.dumps(ack).encode("utf-8"))
        except Exception as error:
            log("[%s] ack write failed: %s" % (device_id, type(error).__name__))
            break

        storage.ingest_telemetry(packet_queue, device_id, inner)
        records += 1

        if expired:
            log("[%s] SESSION AGE LIMIT reached at %.1fs after %d records - "
                "forcing re-handshake (revocation checkpoint)"
                % (device_id, age, records))
            break

    span = time.monotonic() - started
    log("[%s] session closed: %d records in %.1fs (%.2f/s), duplicates %d"
        % (device_id, records, span, records / span if span > 0 else 0.0,
           duplicates))


def handle_peer(ctx, raw, config_store, packet_queue, max_session_age_s,
                handshake_timeout_s, log, on_finished=None, mailbox_db_path=None,
                on_handshake_done=None, identity_db_path=None,
                address_db_path=None):
    """Complete the handshake and serve the session. Runs on its own thread, so
    a peer that goes silent mid-handshake cannot stall the accept loop or any
    other peer's thread.

    handshake_timeout_s is currently unused: an attempt to enforce it by
    calling raw.settimeout() before wrap_socket() broke every real handshake
    against real hardware (100% failure, wolfSSL error -308) although the
    in-memory gate never caught it - see FINDINGS #12. A peer that goes silent
    mid-handshake can still block this thread indefinitely; that narrow leak
    is accepted for now rather than risk this again without a tested fix.

    on_finished releases this peer address so the same device can reconnect
    later; without it the known_peers set would grow forever and a returning
    peer would be ignored.
    """
    conn = None
    try:
        conn = ctx.wrap_socket(raw, server_side=True)
        if on_handshake_done is not None:
            on_handshake_done()
        device_id = peer_common_name(conn)
        if not device_id:
            log("REJECTED: no identity in peer certificate")
            return
        if not config_store.is_allowed(device_id):
            log("REJECTED %s: revoked or not on the allow-list" % device_id)
            return
        if identity_db_path is not None:
            try:
                der = conn.getpeercert(binary_form=True)
            except Exception:
                der = None
            allowed, reason = identity_guard.check(
                identity_db_path, device_id, der, time.time())
            if not allowed:
                log("REJECTED %s: %s" % (device_id, reason))
                return
        # Learn where this device lives, so a live query can call it back
        # without anyone maintaining a map by hand. Recorded only HERE, after
        # the certificate has been verified and the roster checked, so an
        # unauthenticated stranger cannot poison another unit's entry.
        if address_db_path is not None:
            try:
                moved = device_addresses.remember(
                    address_db_path, device_id, raw.getpeername()[0])
                if moved:
                    log("[%s] address learned: %s" % (device_id, raw.getpeername()[0]))
            except Exception as error:
                log("[%s] could not record address: %s" % (device_id, type(error).__name__))

        serve_session(conn, raw, device_id, config_store, packet_queue,
                      max_session_age_s, log, mailbox_db_path=mailbox_db_path)
    except Exception as error:
        log("handshake/session failed: %s: %s" % (type(error).__name__, error))
    finally:
        for closeable in (conn, raw):
            try:
                if closeable is not None:
                    closeable.close()
            except Exception:
                pass
        if on_finished is not None:
            on_finished()
