"""Run the attack suite and write down what actually happened, with evidence.

The gate's SimLab answers "did every check pass?". A memo has to answer a
harder question: "why should I believe you?". So this runs the same attacks
and records the artefacts a reader can check for themselves - the real
ciphertext in hex, the exact refusal message, the row counts before and
after - instead of a green tick.

Everything happens inside a throwaway directory with its own certificate
authority, its own database and invented devices (AMU_01, NMU_01). No real
unit, key or measurement is touched, which is what keeps the project's
experimental data free of numbers that were never measured.

    py -3.12 simlab/attack_report.py

Writes evidence/attack_suite.md and exits non-zero if any attack SUCCEEDED.
"""

import json
import os
import queue
import sys
import tempfile
import threading
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "server"))

import config_store
import dtls_loopback
import storage
from sim_lab import (CIPHERS, SECRET_MARKERS, _build_pki, _one_round_trip,
                     _server_handle_record, _write_config)

OUT_PATH = os.path.join(ROOT, "evidence", "attack_suite.md")
HEX_BYTES = 48


def hexdump(data, limit=HEX_BYTES):
    """A few lines of hex + printable ASCII, the way a capture tool shows it."""
    lines = []
    for offset in range(0, min(len(data), limit), 16):
        chunk = data[offset:offset + 16]
        hexpart = " ".join("%02x" % b for b in chunk)
        text = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        lines.append("%04x  %-47s  %s" % (offset, hexpart, text))
    if len(data) > limit:
        lines.append("....  (%d more bytes)" % (len(data) - limit))
    return "\n".join(lines)


class Report:
    def __init__(self):
        self.sections = []
        self.attacks_defeated = 0
        self.attacks_succeeded = 0

    def add(self, title, attacker_has, attempt, outcome, defeated, evidence):
        self.sections.append({
            "title": title, "attacker_has": attacker_has, "attempt": attempt,
            "outcome": outcome, "defeated": defeated, "evidence": evidence,
        })
        if defeated:
            self.attacks_defeated += 1
        else:
            self.attacks_succeeded += 1

    def render(self, facts):
        out = []
        out.append("# Attack suite: what was tried, and what the system did")
        out.append("")
        out.append("Generated by `simlab/attack_report.py` on %s."
                   % time.strftime("%Y-%m-%d %H:%M:%S"))
        out.append("")
        out.append("## How to read this, and what it does not prove")
        out.append("")
        out.append("Every attack below runs against a complete copy of the "
                   "shipped server code, over a real mutual-authentication "
                   "handshake, inside a throwaway directory with its own "
                   "certificate authority and its own database. The devices "
                   "are invented (`AMU_01`, `NMU_01`); no deployed unit, key "
                   "or measurement is involved, so nothing here can leak an "
                   "unmeasured number into the project's real data.")
        out.append("")
        out.append("**The channel here is DTLS 1.2, not 1.3.** OpenSSL on the "
                   "development machine predates DTLS 1.3, and wolfSSL has no "
                   "Windows build. What is proven here is therefore "
                   "version-independent: mutual authentication, forward "
                   "secrecy, certificate-bound identity, refusal of an "
                   "unknown authority, revocation, and detection of an "
                   "altered record. **DTLS 1.3 itself is proven only on "
                   "hardware**, where the live server and the ESP32 both "
                   "report `DTLSv1.3 / TLS_AES_128_GCM_SHA256`.")
        out.append("")
        out.append("## Session under test")
        out.append("")
        for key, value in facts.items():
            out.append("- **%s**: `%s`" % (key, value))
        out.append("")
        out.append("## Summary")
        out.append("")
        out.append("| # | Attack | Outcome |")
        out.append("|---|---|---|")
        for index, s in enumerate(self.sections, 1):
            verdict = "**defeated**" if s["defeated"] else "**SUCCEEDED**"
            out.append("| %d | %s | %s |" % (index, s["title"], verdict))
        out.append("")
        out.append("**%d of %d attacks defeated.**"
                   % (self.attacks_defeated, len(self.sections)))
        out.append("")
        for index, s in enumerate(self.sections, 1):
            out.append("---")
            out.append("")
            out.append("## %d. %s" % (index, s["title"]))
            out.append("")
            out.append("**The attacker has:** %s" % s["attacker_has"])
            out.append("")
            out.append("**What was attempted:** %s" % s["attempt"])
            out.append("")
            out.append("**What happened:** %s" % s["outcome"])
            out.append("")
            out.append("**Evidence**")
            out.append("")
            out.append("```")
            out.append(s["evidence"])
            out.append("```")
            out.append("")
        return "\n".join(out)


def main():
    tmp = tempfile.mkdtemp(prefix="omega_attack_")
    _build_pki(tmp)
    cfg_path = os.path.join(tmp, "device_config.json")
    _write_config(cfg_path)
    db_file = os.path.join(tmp, "sensor_data.db")
    store = config_store.ConfigStore(cfg_path)
    packet_queue = queue.Queue()
    threading.Thread(target=storage.db_worker, args=(db_file, packet_queue),
                     daemon=True).start()

    report = Report()
    ts = int(time.time())
    facts = {}

    with dtls_loopback.DtlsChannel(tmp, "omega-server", "AMU_01", CIPHERS) as ch:
        info = ch.info()
        facts["cipher suite"] = info.get("cipher")
        facts["server verified the device"] = info.get("client_verify_ok")
        facts["device verified the server"] = info.get("server_verify_ok")
        facts["identity the server derived"] = info.get("server_view_of_client")

        record = {"id": "AMU_01", "type": "airq", "ts": ts, "event": "500_1",
                  "hb": False, "sensors": {"scd30": {"co2_ppm": 612.0}},
                  "cause": "SIM"}
        # Deliberately NOT _one_round_trip here. That helper sends the record
        # and THEN the ACK, so last_wire() hands back the ACK's ciphertext
        # while the caption claims it is the record's - a plausible-looking
        # number measuring the wrong packet. It showed up as 108 bytes of
        # ciphertext for a 139-byte record, which is impossible.
        record_plain = json.dumps(record).encode("utf-8")
        seen = ch.client_to_server(record_plain)
        wire = ch.last_wire()
        _server_handle_record(ch, store, packet_queue, seen)

        found = [m for m in SECRET_MARKERS if m in wire]
        report.add(
            "Eavesdropping on the wire",
            "a full packet capture of every byte between device and server, "
            "and the WLAN password",
            "read the sensor values straight out of the captured traffic",
            "The reading is not recoverable. The record is %d bytes of "
            "readable JSON before encryption and %d bytes on the wire after "
            "it, and none of the searched values appear in what was "
            "transmitted."
            % (len(record_plain), len(wire)),
            not found,
            "plaintext record  : %s\n"
            "plaintext size    : %d bytes\n"
            "ciphertext size   : %d bytes (%+d overhead)\n"
            "searched for      : %s\n"
            "found on the wire : %s\n\n"
            "first %d bytes of the ENCRYPTED RECORD as transmitted:\n%s"
            % (record_plain.decode("utf-8"), len(record_plain), len(wire),
               len(wire) - len(record_plain),
               ", ".join(repr(m) for m in SECRET_MARKERS),
               (", ".join(repr(m) for m in found) if found else "NOTHING"),
               HEX_BYTES, hexdump(wire)))

        spoof = {"id": "NMU_99", "type": "airq", "ts": ts, "event": "500_2",
                 "hb": False, "sensors": {"scd30": {"co2_ppm": 400.0}},
                 "cause": "SPOOF"}
        stored_as, _ = _one_round_trip(ch, store, packet_queue, spoof)
        report.add(
            "A genuine device lying about which unit it is",
            "a valid certificate for AMU_01 and its private key",
            "send a record claiming `\"id\": \"NMU_99\"` so the reading is "
            "filed against a different unit",
            "The lie is ignored. Identity is taken from the certificate the "
            "device authenticated with, never from the message body.",
            stored_as == "AMU_01",
            "claimed in the record : NMU_99\n"
            "certificate presented : AMU_01\n"
            "stored under          : %s" % stored_as)

        replay_event = "500_1"
        _one_round_trip(ch, store, packet_queue, record)
        packet_queue.join()
        conn, cur = storage.open_db(db_file)
        cur.execute("SELECT COUNT(*) FROM air_data WHERE id=? AND event=?",
                    ("AMU_01", replay_event))
        replay_rows = cur.fetchone()[0]
        conn.close()
        report.add(
            "Replaying a captured record",
            "a recorded copy of an earlier, perfectly valid record",
            "send the identical record again to inflate the readings",
            "The duplicate is absorbed. The database keeps one row per "
            "(device, event), so a replay changes nothing.",
            replay_rows == 1,
            "record sent twice     : event %s\n"
            "rows now in database  : %d" % (replay_event, replay_rows))

    with dtls_loopback.DtlsChannel(tmp, "omega-server", "AMU_01", CIPHERS) as ch:
        payload = json.dumps({"id": "AMU_01", "type": "airq", "ts": ts,
                              "event": "500_9", "hb": False,
                              "sensors": {"scd30": {"co2_ppm": 999.0}},
                              "cause": "TAMPER"}).encode("utf-8")
        tampered_wire, accepted = ch.client_to_server_tampered(payload)
        report.add(
            "Man in the middle altering a record in flight",
            "a position on the shared WLAN allowing bytes to be rewritten "
            "as they pass",
            "flip a single bit in the encrypted record so the server stores "
            "a different value than the device sent",
            "The altered record is discarded and never reaches the "
            "application. One bit is enough to invalidate the whole record.",
            not accepted,
            "bits changed on the wire : 1\n"
            "bytes in the record      : %d\n"
            "server accepted it       : %s\n\n"
            "first %d bytes of the altered record:\n%s"
            % (len(tampered_wire), "YES" if accepted else "NO",
               HEX_BYTES, hexdump(tampered_wire)))

    forged_error = ""
    try:
        dtls_loopback.DtlsChannel(tmp, "omega-server", "rogue", CIPHERS).close()
        forged_defeated = False
    except dtls_loopback.HandshakeError as error:
        forged_defeated = True
        forged_error = "%s: %s" % (type(error).__name__, error)
    report.add(
        "A rogue device with a certificate from another authority",
        "the WLAN password, the server's address, and a certificate it "
        "issued to itself",
        "complete the handshake and start submitting readings",
        "The handshake never completes. The certificate is not signed by "
        "this fleet's authority, so the session is refused before any "
        "application data can be sent.",
        forged_defeated,
        "handshake result : %s" % (forged_error or "ACCEPTED - attack succeeded"))

    rogue_live_error = ""
    try:
        dtls_loopback.DtlsChannel(tmp, "AMU_01", "rogue", CIPHERS).close()
        rogue_live_defeated = False
    except dtls_loopback.HandshakeError as error:
        rogue_live_defeated = True
        rogue_live_error = "%s: %s" % (type(error).__name__, error)
    report.add(
        "A rogue operator calling a device directly",
        "network access to the device and a self-issued operator certificate",
        "open the device's live-query channel and command it directly, "
        "bypassing the server",
        "The device refuses the caller. A unit authenticates whoever calls "
        "it by certificate, exactly as the server does.",
        rogue_live_defeated,
        "handshake result : %s"
        % (rogue_live_error or "ACCEPTED - attack succeeded"))

    allowed_before = store.is_allowed("AMU_01")
    allowed_revoked = store.is_allowed("AMU_09")
    report.add(
        "A retired or stolen unit still holding a valid certificate",
        "a genuine, unexpired certificate issued by this fleet's own "
        "authority, and its private key",
        "reconnect after being retired and continue submitting readings",
        "The unit is refused by name. Revocation does not need the "
        "certificate to expire or be recalled from the device.",
        allowed_revoked is False and allowed_before is True,
        "active unit AMU_01  allowed : %s\n"
        "revoked unit AMU_09 allowed : %s" % (allowed_before, allowed_revoked))

    packet_queue.put(None)

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(report.render(facts))

    for index, s in enumerate(report.sections, 1):
        print("  %-9s %d. %s"
              % ("defeated" if s["defeated"] else "SUCCEEDED", index, s["title"]))
    print("%d of %d attacks defeated"
          % (report.attacks_defeated, len(report.sections)))
    print("wrote %s" % OUT_PATH)
    return 0 if report.attacks_succeeded == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
